import { HistoricalEvent } from './types';

export const INITIAL_EVENTS: HistoricalEvent[] = [
  // Ancient History
  { id: '1', title: 'Unification of Upper and Lower Egypt', year: -3100, description: 'Narmer (Menes) unifies Egypt, founding the First Dynasty.', category: 'politics', link: 'https://en.wikipedia.org/wiki/Narmer' },
  { id: '2', title: 'Construction of Great Pyramid of Giza', year: -2560, description: 'Completed for Pharaoh Khufu.', category: 'art', link: 'https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza' },
  { id: '3', title: 'Epic of Gilgamesh Written', year: -2100, description: 'The earliest surviving great work of literature.', category: 'art', link: 'https://en.wikipedia.org/wiki/Epic_of_Gilgamesh' },
  { id: '4', title: 'Code of Hammurabi', year: -1754, description: 'Babylonian law code of ancient Mesopotamia.', category: 'politics', link: 'https://en.wikipedia.org/wiki/Code_of_Hammurabi' },
  { id: '5', title: 'Shang Dynasty established', year: -1600, description: 'The first Chinese dynasty supported by archaeological evidence.', category: 'politics' },
  { id: '6', title: 'Fall of Troy', year: -1184, description: 'Traditional date for the end of the Trojan War.', category: 'war' },
  { id: '7', title: 'David becomes King of Israel', year: -1010, description: 'Unifies the tribes of Israel.', category: 'politics' },
  { id: '8', title: 'Founding of Rome', year: -753, description: 'Legendary founding by Romulus.', category: 'politics' },
  { id: '9', title: 'First Olympiad', year: -776, description: 'First recorded Olympic Games in ancient Greece.', category: 'art' },
  { id: '10', title: 'Fall of Nineveh', year: -612, description: 'Destruction of the Assyrian capital by Babylonians and Medes.', category: 'war' },
  { id: '11', title: 'Birth of Confucius', year: -551, description: 'Chinese philosopher and politician.', category: 'politics' },
  { id: '12', title: 'Roman Republic founded', year: -509, description: 'Overthrow of the Roman monarchy.', category: 'politics' },
  { id: '13', title: 'Battle of Marathon', year: -490, description: 'Athenians defeat the Persians.', category: 'war' },
  { id: '14', title: 'Death of Socrates', year: -399, description: 'Sentenced to death by drinking hemlock.', category: 'politics' },
  { id: '15', title: 'Alexander the Great becomes King', year: -336, description: 'Ascension to the throne of Macedon.', category: 'politics' },
  { id: '16', title: 'Unification of China', year: -221, description: 'Qin Shi Huang establishes the Qin Dynasty.', category: 'politics' },
  { id: '17', title: 'Construction of the Great Wall begins', year: -220, description: 'Qin Shi Huang orders the joining of earlier walls.', category: 'art' },
  { id: '18', title: 'Assassination of Julius Caesar', year: -44, month: 3, description: 'Stabbed by Roman senators on the Ides of March.', category: 'politics' },
  { id: '19', title: 'Battle of Actium', year: -31, description: 'Octavian defeats Mark Antony and Cleopatra.', category: 'war' },
  { id: '20', title: 'Augustus becomes Emperor', year: -27, description: 'Beginning of the Roman Empire.', category: 'politics' },
  
  // 1st Millennium AD
  { id: '21', title: 'Crucifixion of Jesus', year: 33, description: 'Central event in Christianity (approximate date).', category: 'religion' },
  { id: '22', title: 'Great Fire of Rome', year: 64, description: 'Fire destroys much of the city; Nero blames Christians.', category: 'general' },
  { id: '23', title: 'Destruction of Pompeii', year: 79, description: 'Eruption of Mount Vesuvius.', category: 'general' },
  { id: '24', title: 'Paper invented in China', year: 105, description: 'Cai Lun standardizes papermaking.', category: 'science' },
  { id: '25', title: 'Edict of Milan', year: 313, description: 'Constantine I legalizes Christianity in the Roman Empire.', category: 'religion' },
  { id: '26', title: 'Fall of Western Roman Empire', year: 476, description: 'Romulus Augustulus deposed by Odoacer.', category: 'politics' },
  { id: '27', title: 'Hagia Sophia completed', year: 537, description: 'Masterpiece of Byzantine architecture in Constantinople.', category: 'art' },
  { id: '28', title: 'Birth of Muhammad', year: 570, description: 'Founder of Islam.', category: 'religion' },
  { id: '29', title: 'Tang Dynasty founded', year: 618, description: 'Golden age of Chinese arts and culture.', category: 'politics' },
  { id: '30', title: 'Hijra', year: 622, description: 'Muhammad\'s migration from Mecca to Medina.', category: 'religion' },
  { id: '31', title: 'Battle of Tours', year: 732, description: 'Charles Martel stops the Umayyad advance into France.', category: 'war' },
  { id: '32', title: 'Charlemagne crowned Emperor', year: 800, month: 12, description: 'Crowned Imperator Romanorum by Pope Leo III.', category: 'politics' },
  { id: '33', title: 'Treaty of Verdun', year: 843, description: 'Division of the Carolingian Empire.', category: 'politics' },
  { id: '34', title: 'Viking discovery of Iceland', year: 870, description: 'Settlement begins shortly after.', category: 'general' },
  
  // 2nd Millennium AD
  { id: '35', title: 'The Great Schism', year: 1054, description: 'Split between Roman Catholic and Eastern Orthodox churches.', category: 'religion' },
  { id: '36', title: 'Battle of Hastings', year: 1066, description: 'William the Conqueror invades England.', category: 'war' },
  { id: '37', title: 'First Crusade begins', year: 1096, description: 'Military expedition by Western Christianity to regain Holy Lands.', category: 'war' },
  { id: '38', title: 'Magna Carta signed', year: 1215, month: 6, description: 'King John of England agrees to limit his powers.', category: 'politics' },
  { id: '39', title: 'Mongol Sack of Baghdad', year: 1258, description: 'End of the Islamic Golden Age.', category: 'war' },
  { id: '40', title: 'Marco Polo travels to China', year: 1271, description: 'Venetian merchant begins his journey.', category: 'general' },
  { id: '41', title: 'Black Death peaks in Europe', year: 1348, description: 'Plague kills estimated 30-60% of Europe\'s population.', category: 'general' },
  { id: '42', title: 'Gutenberg Printing Press', year: 1440, description: 'Invention of movable type printing.', category: 'science' },
  { id: '43', title: 'Fall of Constantinople', year: 1453, description: 'Ottoman Empire captures the Byzantine capital.', category: 'war' },
  { id: '44', title: 'Columbus lands in Americas', year: 1492, month: 10, description: 'Beginning of widespread European exploration.', category: 'general' },
  { id: '45', title: 'Mona Lisa painted', year: 1503, description: 'Leonardo da Vinci begins his masterpiece.', category: 'art' },
  { id: '46', title: 'Martin Luther\'s 95 Theses', year: 1517, description: 'Start of the Protestant Reformation.', category: 'religion' },
  { id: '47', title: 'Magellan circumnavigation begins', year: 1519, description: 'First expedition to sail around the world.', category: 'general' },
  { id: '48', title: 'Copernicus publishes On the Revolutions', year: 1543, description: 'Heliocentric theory proposed.', category: 'science' },
  { id: '49', title: 'Defeat of the Spanish Armada', year: 1588, description: 'English naval victory under Elizabeth I.', category: 'war' },
  { id: '50', title: 'Jamestown settled', year: 1607, description: 'First permanent English settlement in the Americas.', category: 'politics' },
  { id: '51', title: 'Galileo shows telescope to Doge', year: 1609, description: 'Advancement in astronomy.', category: 'science' },
  { id: '52', title: 'Peace of Westphalia', year: 1648, description: 'Ends the Thirty Years\' War.', category: 'politics' },
  { id: '53', title: 'Isaac Newton publishes Principia', year: 1687, description: 'Foundations of classical mechanics.', category: 'science' },
  { id: '54', title: 'Steam Engine patented', year: 1769, description: 'James Watt improves the steam engine.', category: 'science' },
  { id: '55', title: 'American Declaration of Independence', year: 1776, month: 7, description: 'Colonies declare independence from Britain.', category: 'politics' },
  { id: '56', title: 'French Revolution begins', year: 1789, month: 7, description: 'Storming of the Bastille.', category: 'politics' },
  { id: '57', title: 'Battle of Waterloo', year: 1815, month: 6, description: 'Defeat of Napoleon Bonaparte.', category: 'war' },
  { id: '58', title: 'First Photograph taken', year: 1826, description: 'Joseph Nicéphore Niépce captures "View from the Window at Le Gras".', category: 'art' },
  { id: '59', title: 'Slavery abolished in British Empire', year: 1833, description: 'Slavery Abolition Act.', category: 'politics' },
  { id: '60', title: 'Origin of Species published', year: 1859, description: 'Charles Darwin proposes theory of evolution.', category: 'science' },
  { id: '61', title: 'American Civil War begins', year: 1861, description: 'Confederate forces fire on Fort Sumter.', category: 'war' },
  { id: '62', title: 'Telephone patented', year: 1876, description: 'Alexander Graham Bell awarded patent.', category: 'science' },
  { id: '63', title: 'Eiffel Tower completed', year: 1889, description: 'Built for the 1889 World\'s Fair.', category: 'art' },
  
  // 20th Century
  { id: '64', title: 'Wright Brothers First Flight', year: 1903, month: 12, description: 'First powered flight in Kitty Hawk.', category: 'science' },
  { id: '65', title: 'Titanic Sinks', year: 1912, month: 4, description: 'Maritime disaster in the North Atlantic.', category: 'general' },
  { id: '66', title: 'World War I begins', year: 1914, month: 7, description: 'Assassination of Archduke Franz Ferdinand triggers war.', category: 'war' },
  { id: '67', title: 'Russian Revolution', year: 1917, month: 3, description: 'Overthrow of the Tsarist autocracy.', category: 'politics' },
  { id: '68', title: 'Women\'s Suffrage in US', year: 1920, month: 8, description: '19th Amendment ratified.', category: 'politics' },
  { id: '69', title: 'Penicillin discovered', year: 1928, description: 'Alexander Fleming discovers the first antibiotic.', category: 'science' },
  { id: '70', title: 'Stock Market Crash', year: 1929, month: 10, description: 'Start of the Great Depression.', category: 'general' },
  { id: '71', title: 'Hitler becomes Chancellor', year: 1933, month: 1, description: 'Rise of Nazi Germany.', category: 'politics' },
  { id: '72', title: 'World War II begins', year: 1939, month: 9, description: 'Germany invades Poland.', category: 'war' },
  { id: '73', title: 'Pearl Harbor attack', year: 1941, month: 12, description: 'US enters WWII.', category: 'war' },
  { id: '74', title: 'D-Day', year: 1944, month: 6, description: 'Allied invasion of Normandy.', category: 'war' },
  { id: '75', title: 'Atomic Bomb dropped', year: 1945, month: 8, description: 'Hiroshima and Nagasaki bombed.', category: 'war' },
  { id: '76', title: 'Independence of India', year: 1947, month: 8, description: 'End of British rule in India.', category: 'politics' },
  { id: '77', title: 'Israel founded', year: 1948, month: 5, description: 'Declaration of independence.', category: 'politics' },
  { id: '78', title: 'Communist China established', year: 1949, month: 10, description: 'Mao Zedong proclaims PRC.', category: 'politics' },
  { id: '79', title: 'DNA Structure discovered', year: 1953, description: 'Watson and Crick describe the double helix.', category: 'science' },
  { id: '80', title: 'Sputnik 1 launched', year: 1957, month: 10, description: 'First artificial satellite.', category: 'science' },
  { id: '81', title: 'Cuban Missile Crisis', year: 1962, month: 10, description: 'Peak of Cold War tension.', category: 'politics' },
  { id: '82', title: 'I Have a Dream speech', year: 1963, month: 8, description: 'Martin Luther King Jr. addresses crowd in DC.', category: 'politics' },
  { id: '83', title: 'Moon Landing', year: 1969, month: 7, description: 'Apollo 11 lands on the moon.', category: 'science' },
  { id: '84', title: 'First Microprocessor', year: 1971, description: 'Intel 4004 released.', category: 'science' },
  { id: '85', title: 'End of Vietnam War', year: 1975, month: 4, description: 'Fall of Saigon.', category: 'war' },
  { id: '86', title: 'Smallpox eradicated', year: 1980, description: 'WHO declares the disease eradicated.', category: 'science' },
  { id: '87', title: 'Chernobyl Disaster', year: 1986, month: 4, description: 'Nuclear accident in Ukraine.', category: 'general' },
  { id: '88', title: 'Fall of the Berlin Wall', year: 1989, month: 11, description: 'Symbolic end of the Cold War.', category: 'politics' },
  { id: '89', title: 'World Wide Web publicly available', year: 1991, month: 8, description: 'Tim Berners-Lee publishes the first website.', category: 'science' },
  { id: '90', title: 'End of Apartheid', year: 1994, month: 4, description: 'Nelson Mandela elected President of South Africa.', category: 'politics' },
  { id: '91', title: 'Dolly the Sheep cloned', year: 1996, description: 'First mammal cloned from an adult cell.', category: 'science' },
  { id: '92', title: 'Euro currency introduced', year: 1999, month: 1, description: 'Single currency for the Eurozone.', category: 'politics' },
  
  // 3rd Millennium
  { id: '93', title: 'September 11 Attacks', year: 2001, month: 9, description: 'Terrorist attacks in the US.', category: 'war' },
  { id: '94', title: 'Human Genome Project completed', year: 2003, month: 4, description: 'Full sequencing of human DNA.', category: 'science' },
  { id: '95', title: 'Facebook launched', year: 2004, month: 2, description: 'Rise of social media.', category: 'science' },
  { id: '96', title: 'First iPhone released', year: 2007, month: 6, description: 'Smartphone revolution begins.', category: 'science' },
  { id: '97', title: 'Burj Khalifa opened', year: 2010, month: 1, description: 'Tallest building in the world.', category: 'art' },
  { id: '98', title: 'Arab Spring', year: 2010, month: 12, description: 'Series of anti-government protests.', category: 'politics' },
  { id: '99', title: 'Higgs Boson discovered', year: 2012, month: 7, description: 'CERN confirms existence of the particle.', category: 'science' },
  { id: '100', title: 'Paris Agreement', year: 2015, month: 12, description: 'Global agreement on climate change.', category: 'politics' },
  { id: '101', title: 'First Image of Black Hole', year: 2019, month: 4, description: 'Event Horizon Telescope captures M87.', category: 'science' },
  { id: '102', title: 'COVID-19 Pandemic declared', year: 2020, month: 3, description: 'Global health crisis.', category: 'general' },
  { id: '103', title: 'James Webb Telescope Launch', year: 2021, month: 12, description: 'Successor to Hubble.', category: 'science' },
  { id: '104', title: 'Rise of Generative AI', year: 2023, description: 'Public adoption of LLMs like GPT and Gemini.', category: 'science' },
];
